meta_product_name: "Xplorerz"
meta_title: "Find a itinerary for the perfect journey"
meta_description: "The xplorerz community is constantly striving to create the best travel itineraries and get the most love in return. Start to create awesome itineraries now : you might even become the expert of a country, a continent and maybe the entire world."
meta_image: "itinerary-logo-resized.jpg" # should exist in `app/assets/images/`
